addons:
  postgresql: 9.3
rvm:
  - 1.9.3
  - 2.1.1
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
script: "bundle exec rspec spec"
bundler_args: '--no-deployment'
notifications:
  slack: papercloud:SDpE0qusrXrC49QBryGVcR2B
