addons:
  postgresql: 9.3
rvm:
  - 1.9.3
  - 2.1.1
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
script: "bundle exec rspec spec"
bundler_args: '--no-deployment'