development:
  adapter: postgresql
  encoding: unicode
  database: notify_user_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: notify_user_test
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: notify_user_production
  pool: 5
  timeout: 5000
