development:
  adapter: postgresql
  encoding: unicode
  database: notify_user_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: notify_user_test
  host: localhost
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: notify_user_production
  host: localhost
  pool: 5
  timeout: 5000
